config/routes.rb
Rails.application.routes.draw do
  get 'password_reset/new'
  get 'password_reset/edit'
  get 'sessions/new'
  get 'user_infos/new'
  get 'users/new'
  root 'static_pages#home'
  get '/help',   to: 'static_pages#help'
  get '/about',  to: 'static_pages#about'
  get '/contact',to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout' , to: 'sessions#destroy'
  # get 'hello' => 'hello#index'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_reset, only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        <a href="http://railstutorial.org/">Rails Tutorial</a>
        by Michael Hartl
    </small>
    <nav>
        <ul>
        <li><%= link_to "About",   '/about' %></li>
        <li><%= link_to "Contact", '/contact' %></li>
        <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <%= link_to "sample app", '/', id: "logo" %>
            <nav>
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Home",    '/' %></li>
                    <li><%= link_to "Help",    '/help' %></li>
                    <% if logged_in? %>
                        <li><%= link_to "Users",   users_path %></li>
                        <li class="dropdown">
                            <a href='#' class='dropdown-toggle' data-toggle="dropdown">
                                Account <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Profile",   user_path(current_user) %></li>
                                <li><%= link_to "Settings",  edit_user_path(current_user) %></li>
                                <li class="divider"></li>
                                <li>
                                    <%= link_to "Log out",   logout_path, method: :delete %>
                                </li>
                            </ul>
                        </li>
                        <% else %>
                            <li><%= link_to "Log in", '/login' %></li>
                    <% end %>
                </ul>
            </nav>
        </div>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title)%> | Ruby on Rails Tutorial Sample App</title>
        <%= stylesheet_link_tag "application", media: "all",
                                            "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>

        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
        <% flash.each do |message_type, message| %>
            <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
        </div>
        <%= render 'layouts/footer'%>
        <%= debug(params) if Rails.env.development? %>
    </body>
</html>